# Generated by Django 5.1.6 on 2025-02-22 03:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('paginas', models.IntegerField()),
                ('capa', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('sinopse', models.TextField(max_length=1000)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
                ('editora', models.CharField(max_length=100)),
                ('autor', models.CharField(max_length=100)),
                ('data_cadastro', models.DateTimeField(default=datetime.datetime.now)),
                ('data_emprestado', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('data_devolução', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ano_publicado', models.IntegerField()),
            ],
        ),
    ]
