# Generated by Django 5.1.6 on 2025-02-22 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='data_devolução',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='data_emprestado',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
