# Generated by Django 5.1.6 on 2025-02-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_categoria_remove_livro_categoria_livro_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(max_length=2000),
        ),
    ]
