# Generated by Django 5.1.6 on 2025-02-24 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_livro_sinopse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='data_devolução',
            new_name='data_devolucao',
        ),
    ]
