# Generated by Django 5.1.6 on 2025-03-01 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoSolarPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons_jan', models.IntegerField(verbose_name='Consumo (kWh) Janeiro')),
                ('cons_fev', models.IntegerField(verbose_name='Consumo (kWh) Fevereiro')),
                ('cons_mar', models.IntegerField(verbose_name='Consumo (kWh) Março')),
                ('cons_abr', models.IntegerField(verbose_name='Consumo (kWh) Abril')),
                ('cons_mai', models.IntegerField(verbose_name='Consumo (kWh) Maio')),
                ('cons_jun', models.IntegerField(verbose_name='Consumo (kWh) Junho')),
                ('cons_jul', models.IntegerField(verbose_name='Consumo (kWh) Julho')),
                ('cons_ago', models.IntegerField(verbose_name='Consumo (kWh) Agosto')),
                ('cons_set', models.IntegerField(verbose_name='Consumo (kWh) Setembro')),
                ('cons_out', models.IntegerField(verbose_name='Consumo (kWh) Outubro')),
                ('cons_nov', models.IntegerField(verbose_name='Consumo (kWh) Novembro')),
                ('cons_dez', models.IntegerField(verbose_name='Consumo (kWh) Dezembro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepf')),
            ],
            options={
                'verbose_name': 'Cálculo Solar PF',
                'verbose_name_plural': 'Cálculos Solares PF',
                'ordering': ['-id'],
            },
        ),
    ]
