# Generated by Django 5.1.6 on 2025-03-01 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculosolarpf',
            options={'ordering': ['-id'], 'verbose_name': 'Cálculo Irradiancia Média', 'verbose_name_plural': 'Cálculos Irradiancias Médias'},
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_abr',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_ago',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_dez',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_fev',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_jan',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_jul',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_jun',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_mai',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_mar',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_nov',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_out',
        ),
        migrations.RemoveField(
            model_name='calculosolarpf',
            name='cons_set',
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_abr',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Abril'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_ago',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Agosto'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_dez',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Dezembro'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_fev',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Fevereiro'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_jan',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Janeiro'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_jul',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Julho'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_jun',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Junho'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_mai',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Maio'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_mar',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Março'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_nov',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Novembro'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_out',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Outubro'),
        ),
        migrations.AddField(
            model_name='calculosolarpf',
            name='irradi_set',
            field=models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Setembro'),
        ),
        migrations.CreateModel(
            name='CalculoIrradianciaSolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irradi_jan', models.IntegerField(default=0, verbose_name='Irradiancia Janeiro')),
                ('irradi_fev', models.IntegerField(default=0, verbose_name='Irradiancia Fevereiro')),
                ('irradi_mar', models.IntegerField(default=0, verbose_name='Irradiancia Março')),
                ('irradi_abr', models.IntegerField(default=0, verbose_name='Irradiancia Abril')),
                ('irradi_mai', models.IntegerField(default=0, verbose_name='Irradiancia Maio')),
                ('irradi_jun', models.IntegerField(default=0, verbose_name='Irradiancia Junho')),
                ('irradi_jul', models.IntegerField(default=0, verbose_name='Irradiancia Julho')),
                ('irradi_ago', models.IntegerField(default=0, verbose_name='Irradiancia Agosto')),
                ('irradi_set', models.IntegerField(default=0, verbose_name='Irradiancia Setembro')),
                ('irradi_out', models.IntegerField(default=0, verbose_name='Irradiancia Outubro')),
                ('irradi_nov', models.IntegerField(default=0, verbose_name='Irradiancia Novembro')),
                ('irradi_dez', models.IntegerField(default=0, verbose_name='Irradiancia Dezembro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepf')),
            ],
            options={
                'verbose_name': 'Cálculo Irradiancia Média',
                'verbose_name_plural': 'Cálculos Irradiancias Médias',
                'ordering': ['-id'],
            },
        ),
    ]
