# Generated by Django 5.1.6 on 2025-03-01 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0002_alter_calculosolarpf_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculosolarpf',
            options={'ordering': ['-id'], 'verbose_name': 'Cálculo Consumo Médio', 'verbose_name_plural': 'Cálculos Consumos Médios'},
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_abr',
            new_name='cons_abr',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_ago',
            new_name='cons_ago',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_dez',
            new_name='cons_dez',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_fev',
            new_name='cons_fev',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_jan',
            new_name='cons_jan',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_jul',
            new_name='cons_jul',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_jun',
            new_name='cons_jun',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_mai',
            new_name='cons_mai',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_mar',
            new_name='cons_mar',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_nov',
            new_name='cons_nov',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_out',
            new_name='cons_out',
        ),
        migrations.RenameField(
            model_name='calculosolarpf',
            old_name='irradi_set',
            new_name='cons_set',
        ),
    ]
