# Generated by Django 5.1.6 on 2025-03-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0003_alter_calculosolarpf_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_abr',
            field=models.FloatField(default=0, verbose_name='Irradiancia Abril'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_ago',
            field=models.FloatField(default=0, verbose_name='Irradiancia Agosto'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_dez',
            field=models.FloatField(default=0, verbose_name='Irradiancia Dezembro'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_fev',
            field=models.FloatField(default=0, verbose_name='Irradiancia Fevereiro'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_jan',
            field=models.FloatField(default=0, verbose_name='Irradiancia Janeiro'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_jul',
            field=models.FloatField(default=0, verbose_name='Irradiancia Julho'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_jun',
            field=models.FloatField(default=0, verbose_name='Irradiancia Junho'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_mai',
            field=models.FloatField(default=0, verbose_name='Irradiancia Maio'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_mar',
            field=models.FloatField(default=0, verbose_name='Irradiancia Março'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_nov',
            field=models.FloatField(default=0, verbose_name='Irradiancia Novembro'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_out',
            field=models.FloatField(default=0, verbose_name='Irradiancia Outubro'),
        ),
        migrations.AlterField(
            model_name='calculoirradianciasolar',
            name='irradi_set',
            field=models.FloatField(default=0, verbose_name='Irradiancia Setembro'),
        ),
    ]
