# Generated by Django 5.1.6 on 2025-03-01 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0004_alter_calculoirradianciasolar_irradi_abr_and_more'),
        ('clientes', '0003_remove_clientepf_coordernada_o_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoPotenciaGeracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoSolarPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons_jan', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Janeiro')),
                ('cons_fev', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Fevereiro')),
                ('cons_mar', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Março')),
                ('cons_abr', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Abril')),
                ('cons_mai', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Maio')),
                ('cons_jun', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Junho')),
                ('cons_jul', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Julho')),
                ('cons_ago', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Agosto')),
                ('cons_set', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Setembro')),
                ('cons_out', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Outubro')),
                ('cons_nov', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Novembro')),
                ('cons_dez', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Dezembro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepj')),
            ],
            options={
                'verbose_name': 'Cálculo Consumo Médio',
                'verbose_name_plural': 'Cálculos Consumos Médios',
                'ordering': ['-id'],
            },
        ),
    ]
