# Generated by Django 5.1.6 on 2025-03-01 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0005_calculopotenciageracao_calculosolarpj'),
        ('clientes', '0003_remove_clientepf_coordernada_o_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalcPotenciaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='CalculoPotenciaGeracao',
            new_name='AdicaoPotenciaKWHMes',
        ),
        migrations.AlterModelOptions(
            name='calculosolarpf',
            options={'ordering': ['-id'], 'verbose_name': 'Cálculo Consumo Médio PF', 'verbose_name_plural': 'Cálculos Consumos Médios PFs'},
        ),
        migrations.AlterModelOptions(
            name='calculosolarpj',
            options={'ordering': ['-id'], 'verbose_name': 'Cálculo Consumo Médio PJ', 'verbose_name_plural': 'Cálculos Consumos Médios PJs'},
        ),
        migrations.CreateModel(
            name='CalculoPotenciaGeracaoPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimento', models.IntegerField(default=100, verbose_name='Rendimento do Sistema %')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepf')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolarpf')),
                ('irradi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculoirradianciasolar', verbose_name='Irradiação Solar')),
            ],
        ),
    ]
