# Generated by Django 5.1.6 on 2025-03-01 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0006_calcpotenciaadicional_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculopotenciageracaopf',
            options={'ordering': ['-id'], 'verbose_name': 'Potência de Geração Necessária PF', 'verbose_name_plural': 'Potências de Geração Necessárias PFs'},
        ),
        migrations.AlterModelOptions(
            name='calculosolarpf',
            options={'ordering': ['-id'], 'verbose_name': 'Consumo Médio PF', 'verbose_name_plural': 'Consumos Médios PFs'},
        ),
        migrations.AlterModelOptions(
            name='calculosolarpj',
            options={'ordering': ['-id'], 'verbose_name': 'Consumo Médio PJ', 'verbose_name_plural': 'Consumos Médios PJs'},
        ),
    ]
