# Generated by Django 5.1.6 on 2025-03-01 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0007_alter_calculopotenciageracaopf_options_and_more'),
        ('clientes', '0003_remove_clientepf_coordernada_o_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QntPaineisPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QntPaineisPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CalculoPotenciaGeracaoPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimento', models.IntegerField(default=100, verbose_name='Rendimento do Sistema %')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepj')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolarpj')),
                ('irradi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculoirradianciasolar', verbose_name='Irradiação Solar')),
            ],
            options={
                'verbose_name': 'Potência de Geração Necessária PF',
                'verbose_name_plural': 'Potências de Geração Necessárias PFs',
                'ordering': ['-id'],
            },
        ),
    ]
