# Generated by Django 5.1.6 on 2025-03-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0008_qntpaineispf_qntpaineispj_calculopotenciageracaopj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculoirradianciasolar',
            name='cliente',
        ),
        migrations.AddField(
            model_name='calculoirradianciasolar',
            name='bairro',
            field=models.CharField(default='', max_length=200),
        ),
    ]
