# Generated by Django 5.1.6 on 2025-03-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0009_remove_calculoirradianciasolar_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculoirradianciasolar',
            options={'ordering': ['-id'], 'verbose_name': 'Irradiancia Média', 'verbose_name_plural': 'Irradiancias Médias'},
        ),
    ]
