# Generated by Django 5.1.6 on 2025-03-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0011_calculoirradianciasolar_cidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calculopotenciageracaopj',
            options={'ordering': ['-id'], 'verbose_name': 'Potência de Geração Necessária PJ', 'verbose_name_plural': 'Potências de Geração Necessárias PJs'},
        ),
    ]
