# Generated by Django 5.1.6 on 2025-03-03 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0012_alter_calculopotenciageracaopj_options'),
        ('clientes', '0003_remove_clientepf_coordernada_o_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qntpaineispf',
            options={'ordering': ['-id'], 'verbose_name': 'Quantdade de Painel Necessário PF', 'verbose_name_plural': 'Quantdade de Paineis Necessários PFs'},
        ),
        migrations.AlterModelOptions(
            name='qntpaineispj',
            options={'ordering': ['-id'], 'verbose_name': 'Quantdade de Painel Necessário PJ', 'verbose_name_plural': 'Quantdade de Paineis Necessários PJs'},
        ),
        migrations.AddField(
            model_name='qntpaineispf',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepf'),
        ),
        migrations.AddField(
            model_name='qntpaineispf',
            name='potgeracao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculopotenciageracaopf', verbose_name='Potência de Geração'),
        ),
        migrations.AddField(
            model_name='qntpaineispf',
            name='potpainel',
            field=models.IntegerField(default=0, verbose_name='Potencia do Painel'),
        ),
        migrations.AddField(
            model_name='qntpaineispj',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepj'),
        ),
        migrations.AddField(
            model_name='qntpaineispj',
            name='potgeracao',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculopotenciageracaopj', verbose_name='Potência de Geração'),
        ),
        migrations.AddField(
            model_name='qntpaineispj',
            name='potpainel',
            field=models.IntegerField(default=0, verbose_name='Potencia do Painel'),
        ),
    ]
