# Generated by Django 5.1.6 on 2025-03-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0013_alter_qntpaineispf_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qntpaineispf',
            name='potpainel',
            field=models.IntegerField(default=0, verbose_name='Potencia do Painel (W)'),
        ),
        migrations.AlterField(
            model_name='qntpaineispj',
            name='potpainel',
            field=models.IntegerField(default=0, verbose_name='Potencia do Painel (W)'),
        ),
    ]
