# Generated by Django 5.1.6 on 2025-03-03 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0014_alter_qntpaineispf_potpainel_and_more'),
        ('clientes', '0003_remove_clientepf_coordernada_o_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeracaoPrevistaPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepf')),
                ('irrad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculoirradianciasolar')),
                ('potsist', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculosolar.qntpaineispf')),
                ('rend', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculopotenciageracaopf')),
            ],
        ),
    ]
