# Generated by Django 5.1.6 on 2025-03-03 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0015_geracaoprevistapf'),
        ('clientes', '0003_remove_clientepf_coordernada_o_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepf'),
        ),
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='irrad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculoirradianciasolar'),
        ),
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='potsist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.qntpaineispf'),
        ),
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='rend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculopotenciageracaopf'),
        ),
    ]
