# Generated by Django 5.1.6 on 2025-03-03 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0016_alter_geracaoprevistapf_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='irrad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculoirradianciasolar', verbose_name='Irradiância Local'),
        ),
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='potsist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.qntpaineispf', verbose_name='Potencia do Sistema'),
        ),
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='rend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculopotenciageracaopf', verbose_name='Rendimento'),
        ),
    ]
