# Generated by Django 5.1.6 on 2025-03-03 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0017_alter_geracaoprevistapf_irrad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qntpaineispj',
            name='potgeracao',
        ),
        migrations.RemoveField(
            model_name='calculosolarpj',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='qntpaineispj',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='CalculoPotenciaGeracaoPJ',
        ),
        migrations.DeleteModel(
            name='CalculoSolarPJ',
        ),
        migrations.DeleteModel(
            name='QntPaineisPJ',
        ),
    ]
