# Generated by Django 5.1.6 on 2025-03-03 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0018_remove_qntpaineispj_potgeracao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geracaoprevistapf',
            name='paineisdesejados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='potsist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.qntpaineispf', verbose_name='Numero de Paineis no Sistema'),
        ),
    ]
