# Generated by Django 5.1.6 on 2025-03-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0019_geracaoprevistapf_paineisdesejados_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='paineisdesejados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Paineis Desejada'),
        ),
    ]
