# Generated by Django 5.1.6 on 2025-03-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0020_alter_geracaoprevistapf_paineisdesejados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='potsist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.qntpaineispf', verbose_name='Numero ideal de Paineis no Sistema'),
        ),
    ]
