# Generated by Django 5.1.6 on 2025-03-03 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0021_alter_geracaoprevistapf_potsist'),
        ('clientes', '0004_clientepj_coordenada_o_clientepj_coordenada_s_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicaopotenciakwhmes',
            options={'verbose_name': 'Adição de Potência', 'verbose_name_plural': 'Adição de Potências'},
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolarpf'),
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='consumo',
            field=models.FloatField(default=0, verbose_name='Consumo (kWh/mes)'),
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='dias',
            field=models.FloatField(default=0, verbose_name='Dias uso mês'),
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='equipamento',
            field=models.CharField(default='-', max_length=100, verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='horas',
            field=models.FloatField(default=0, verbose_name='Horas de Uso por dia'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepf'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='equipamento',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='calculopotenciageracaopf',
            name='rendimento',
            field=models.IntegerField(default=100, verbose_name='Eficiência do Sistema %'),
        ),
        migrations.AlterField(
            model_name='geracaoprevistapf',
            name='rend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculopotenciageracaopf', verbose_name='Eficiência'),
        ),
    ]
