# Generated by Django 5.1.6 on 2025-03-03 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0023_alter_adicaopotenciakwhmes_cliente'),
        ('clientes', '0004_clientepj_coordenada_o_clientepj_coordenada_s_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcpotenciaadicional',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepf'),
        ),
    ]
