# Generated by Django 5.1.6 on 2025-03-03 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0025_alter_qntpaineispf_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qntpaineispf',
            name='potgeracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculopotenciageracaopf', verbose_name='Potência de Geração'),
        ),
    ]
