# Generated by Django 5.1.6 on 2025-03-03 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0027_alter_adicaopotenciakwhmes_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculopotenciageracaopf',
            name='consumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolarpf'),
        ),
    ]
