# Generated by Django 5.1.6 on 2025-03-03 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0028_alter_calculopotenciageracaopf_consumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicaopotenciakwhmes',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolarpf'),
        ),
        migrations.AlterField(
            model_name='calculopotenciageracaopf',
            name='consumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolarpf', verbose_name='Consumo Base'),
        ),
    ]
