# Generated by Django 5.1.6 on 2025-03-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0029_alter_adicaopotenciakwhmes_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicaopotenciakwhmes',
            name='consumo',
            field=models.FloatField(blank=True, null=True, verbose_name='Consumo (kWh/mes)'),
        ),
        migrations.AlterField(
            model_name='adicaopotenciakwhmes',
            name='dias',
            field=models.FloatField(blank=True, null=True, verbose_name='Dias uso mês'),
        ),
        migrations.AlterField(
            model_name='adicaopotenciakwhmes',
            name='equipamento',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='adicaopotenciakwhmes',
            name='horas',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas de Uso por dia'),
        ),
    ]
