# Generated by Django 5.1.6 on 2025-03-04 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0030_alter_adicaopotenciakwhmes_consumo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicaopotenciakwhmes',
            options={'verbose_name': 'Adição de consumo por kWh/mes do equipamento', 'verbose_name_plural': 'Adições de consumo por kWh/mes dos equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='calcpotenciaadicional',
            options={'verbose_name': 'Adição de consumo pela Potência do equipamento', 'verbose_name_plural': 'Adições de consumo pela Potência dos equipamentos'},
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='dias',
            field=models.FloatField(blank=True, null=True, verbose_name='Dias uso mês'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='horas',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas de Uso por dia'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='pot',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Potência em Watts do equipamento'),
        ),
        migrations.AlterField(
            model_name='calcpotenciaadicional',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculosolarpf'),
        ),
        migrations.AlterField(
            model_name='calcpotenciaadicional',
            name='equipamento',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Equipamento'),
        ),
    ]
