# Generated by Django 5.1.6 on 2025-03-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0032_alter_calcpotenciaadicional_pot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calcpotenciaadicional',
            name='pot',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Potência do equipamento (Watts)'),
        ),
    ]
