# Generated by Django 5.1.6 on 2025-03-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0033_alter_calcpotenciaadicional_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='minutos',
            field=models.FloatField(blank=True, null=True, verbose_name='Minutos de Uso por dia'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='minutos',
            field=models.FloatField(blank=True, null=True, verbose_name='Minutos de Uso por dia'),
        ),
    ]
