# Generated by Django 5.1.6 on 2025-03-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0034_adicaopotenciakwhmes_minutos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicaopotenciakwhmes',
            name='horas',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Horas de Uso por dia'),
        ),
        migrations.AlterField(
            model_name='adicaopotenciakwhmes',
            name='minutos',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Minutos de Uso por dia'),
        ),
    ]
