# Generated by Django 5.1.6 on 2025-03-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0035_alter_adicaopotenciakwhmes_horas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicaopotenciakwhmes',
            name='horas',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas de Uso por dia'),
        ),
        migrations.AlterField(
            model_name='adicaopotenciakwhmes',
            name='minutos',
            field=models.FloatField(blank=True, null=True, verbose_name='Minutos de Uso por dia'),
        ),
    ]
