# Generated by Django 5.1.6 on 2025-03-03 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculosolar', '0018_remove_qntpaineispj_potgeracao_and_more'),
        ('clientes', '0003_remove_clientepf_coordernada_o_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoSolarPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cons_jan', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Janeiro')),
                ('cons_fev', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Fevereiro')),
                ('cons_mar', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Março')),
                ('cons_abr', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Abril')),
                ('cons_mai', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Maio')),
                ('cons_jun', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Junho')),
                ('cons_jul', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Julho')),
                ('cons_ago', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Agosto')),
                ('cons_set', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Setembro')),
                ('cons_out', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Outubro')),
                ('cons_nov', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Novembro')),
                ('cons_dez', models.IntegerField(default=0, verbose_name='Irradiancia (kWh) Dezembro')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepj')),
            ],
            options={
                'verbose_name': 'Consumo Médio PJ',
                'verbose_name_plural': 'Consumos Médios PJs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CalculoPotenciaGeracaoPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendimento', models.IntegerField(default=100, verbose_name='Rendimento do Sistema %')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepj')),
                ('irradi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculoirradianciasolar', verbose_name='Irradiação Solar')),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.calculosolarpj')),
            ],
            options={
                'verbose_name': 'Potência de Geração Necessária PJ',
                'verbose_name_plural': 'Potências de Geração Necessárias PJs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QntPaineisPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potpainel', models.IntegerField(default=0, verbose_name='Potencia do Painel (W)')),
                ('cliente', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepj')),
                ('potgeracao', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.calculopotenciageracaopj', verbose_name='Potência de Geração')),
            ],
            options={
                'verbose_name': 'Quantdade de Painel Necessário PJ',
                'verbose_name_plural': 'Quantdade de Paineis Necessários PJs',
                'ordering': ['-id'],
            },
        ),
    ]
