# Generated by Django 5.1.6 on 2025-03-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolar', '0018_remove_qntpaineispj_potgeracao_and_more'),
        ('calculosolarpj', '0001_initial'),
        ('clientes', '0003_remove_clientepf_coordernada_o_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicaoPotenciaKWHMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CalcPotenciaAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GeracaoPrevistaPJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepj')),
                ('irrad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolar.calculoirradianciasolar', verbose_name='Irradiância Local')),
                ('potsist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.qntpaineispj', verbose_name='Potencia do Sistema')),
                ('rend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.calculopotenciageracaopj', verbose_name='Rendimento')),
            ],
        ),
    ]
