# Generated by Django 5.1.6 on 2025-03-03 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolarpj', '0002_adicaopotenciakwhmes_calcpotenciaadicional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geracaoprevistapj',
            name='paineisdesejados',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de Paineis Desejada'),
        ),
        migrations.AlterField(
            model_name='geracaoprevistapj',
            name='potsist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.qntpaineispj', verbose_name='Numero ideal de Paineis no Sistema'),
        ),
    ]
