# Generated by Django 5.1.6 on 2025-03-04 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolarpj', '0003_geracaoprevistapj_paineisdesejados_and_more'),
        ('clientes', '0004_clientepj_coordenada_o_clientepj_coordenada_s_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicaopotenciakwhmes',
            options={'verbose_name': 'Adição de consumo por kWh/mes do equipamento', 'verbose_name_plural': 'Adições de consumo por kWh/mes dos equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='calcpotenciaadicional',
            options={'verbose_name': 'Adição de consumo pela Potência do equipamento', 'verbose_name_plural': 'Adições de consumo pela Potência dos equipamentos'},
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.calculosolarpj'),
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='consumo',
            field=models.FloatField(blank=True, null=True, verbose_name='Consumo (kWh/mes)'),
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='dias',
            field=models.FloatField(blank=True, null=True, verbose_name='Dias uso mês'),
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='equipamento',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='horas',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas de Uso por dia'),
        ),
        migrations.AddField(
            model_name='adicaopotenciakwhmes',
            name='minutos',
            field=models.FloatField(blank=True, null=True, verbose_name='Minutos de Uso por dia'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.calculosolarpj'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='dias',
            field=models.FloatField(blank=True, null=True, verbose_name='Dias uso mês'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='equipamento',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='horas',
            field=models.FloatField(blank=True, null=True, verbose_name='Horas de Uso por dia'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='minutos',
            field=models.FloatField(blank=True, null=True, verbose_name='Minutos de Uso por dia'),
        ),
        migrations.AddField(
            model_name='calcpotenciaadicional',
            name='pot',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='Potência do equipamento (Watts)'),
        ),
        migrations.AlterField(
            model_name='calculopotenciageracaopj',
            name='consumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.calculosolarpj', verbose_name='Consumo Base'),
        ),
        migrations.AlterField(
            model_name='calculopotenciageracaopj',
            name='rendimento',
            field=models.IntegerField(default=100, verbose_name='Eficiência do Sistema %'),
        ),
        migrations.AlterField(
            model_name='geracaoprevistapj',
            name='rend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.calculopotenciageracaopj', verbose_name='Eficiência'),
        ),
        migrations.AlterField(
            model_name='qntpaineispj',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientepj'),
        ),
        migrations.AlterField(
            model_name='qntpaineispj',
            name='potgeracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculosolarpj.calculopotenciageracaopj', verbose_name='Potência de Geração'),
        ),
    ]
