# Generated by Django 5.1.6 on 2025-03-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculosolarpj', '0004_alter_adicaopotenciakwhmes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_abr',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Abril'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_ago',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Agosto'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_dez',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Dezembro'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_fev',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Fevereiro'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_jan',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Janeiro'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_jul',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Julho'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_jun',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Junho'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_mai',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Maio'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_mar',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Março'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_nov',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Novembro'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_out',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Outubro'),
        ),
        migrations.AlterField(
            model_name='calculosolarpj',
            name='cons_set',
            field=models.IntegerField(default=0, verbose_name='Consumo (kWh) Setembro'),
        ),
    ]
