# Generated by Django 5.1.6 on 2025-02-24 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('CARRO', 'Carro'), ('MOTO', 'Moto'), ('ÔNIBUS', 'Ônibus'), ('CAMINHÃO', 'Caminhão')], max_length=100)),
                ('tipo_carro', models.CharField(choices=[('SUV', 'SUV'), ('SUV COMPACTO', 'SUV Compacto'), ('HATCH', 'Hatch'), ('PICAPE', 'Picape'), ('SEDÃ', 'Sedã'), ('MINIVAN', 'Minivan'), ('ESPORTIVO', 'Esportivo'), ('FURGÃO', 'Furgão')], max_length=100)),
                ('tipo_moto', models.CharField(choices=[('ESPORTIVA', 'Esportiva'), ('CUSTOM', ' Custom'), ('STREET', 'Street'), ('SCOOTER', 'Scooter'), ('NAKED', 'Naked'), ('TOURING', 'Touring'), ('OFF-ROAD', 'Off-Road')], max_length=100)),
                ('tipo_caminhao', models.CharField(choices=[('BAÚ', 'Baú'), ('CARRETA', 'Carreta'), ('TOCO', 'Toco'), ('Truck', 'Truck')], max_length=100)),
                ('tipo_carreta', models.CharField(choices=[('2 EIXOS', '2 Eixos'), ('3 EIXOS', '3 Eixos'), ('CAVALO TRUCADO', 'Cavalo Trucado'), ('BITREM', 'Bitrem'), ('RODOTREM', 'Rodotrem')], max_length=100)),
                ('tipo_onibus', models.CharField(choices=[('MICROÔNIBUS', 'Micro Ônibus'), ('CONVêNCIONAL', 'Convêncional'), ('SEMI LEITO', 'Semi Leito'), ('LEITO', 'Leito'), ('LEITO-CAMA', 'Leito-Cama'), ('EXECUTIVO', 'Executivo')], max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('n_rodas', models.IntegerField()),
                ('n_portas', models.IntegerField()),
                ('n_passageiros', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
                ('ligado', models.BooleanField(default=True)),
                ('placa', models.CharField(max_length=9)),
                ('foto_carro', models.ImageField(blank=True, upload_to='veiculos/%Y/%m/%d/')),
                ('data_publicado', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
