# Generated by Django 5.1.6 on 2025-02-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculos',
            name='tipo_caminhao',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='tipo_carreta',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='tipo_carro',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='tipo_moto',
        ),
    ]
