# Generated by Django 5.1.6 on 2025-02-24 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_remove_veiculos_tipo_caminhao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculos',
            name='tipo_onibus',
        ),
    ]
