# Generated by Django 5.1.6 on 2025-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_remove_veiculos_tipo_onibus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculos',
            options={'verbose_name_plural': 'Veículos'},
        ),
        migrations.AddField(
            model_name='veiculos',
            name='tipo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='veiculos',
            name='tipo_carreta',
            field=models.CharField(blank=True, choices=[('2_EIXOS', '2 Eixos'), ('3_EIXOS', '3 Eixos'), ('CAVALO TRUCADO', 'Cavalo Trucado'), ('BITREM', 'Bitrem'), ('RODOTREM', 'Rodotrem')], max_length=100, null=True),
        ),
    ]
