# Generated by Django 5.1.6 on 2025-02-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_alter_veiculos_options_veiculos_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculos',
            options={},
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='tipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='tipo_carreta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
