# Generated by Django 5.1.6 on 2025-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0005_alter_veiculos_options_alter_veiculos_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='tipo_carreta',
        ),
        migrations.AddField(
            model_name='veiculos',
            name='caracteristicas',
            field=models.CharField(default='', max_length=200),
        ),
    ]
