# Generated by Django 5.1.6 on 2025-02-26 14:41

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0006_remove_veiculos_tipo_remove_veiculos_tipo_carreta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='veiculos',
            name='caracteristicas',
        ),
        migrations.AlterField(
            model_name='veiculos',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.categoria'),
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='veiculos.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='veiculos',
            name='tipo',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='categoria', chained_model_field='categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='veiculos.tipo'),
        ),
    ]
