# Generated by Django 5.1.6 on 2025-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0007_categoria_remove_veiculos_caracteristicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='caracteristica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
