# Generated by Django 5.1.6 on 2025-02-28 21:43

import clientes.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(max_length=200)),
                ('data_nascimento', models.DateField()),
                ('celular', models.CharField(max_length=14)),
                ('data_cadastro', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Clientes PF',
            },
        ),
        migrations.CreateModel(
            name='ClientePJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ ')),
                ('email', models.EmailField(max_length=200)),
                ('celular', models.CharField(max_length=14)),
                ('data_cadastro', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Clientes PJ',
            },
        ),
        migrations.CreateModel(
            name='ContaClientePFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif']), clientes.models.validate_file_mimetype, clientes.models.validate_file_size], verbose_name='Arquivo (PDF ou imagem)')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='clientes.clientepf')),
            ],
        ),
        migrations.CreateModel(
            name='ContaClientePJFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='uploadspj/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'gif']), clientes.models.validate_file_mimetype, clientes.models.validate_file_size], verbose_name='Arquivo (PDF ou imagem)')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='clientes.clientepj')),
            ],
        ),
    ]
