# Generated by Django 5.1.6 on 2025-03-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepf',
            name='coordenada_s',
            field=models.CharField(default='', max_length=9, verbose_name='Coordenada Sul'),
        ),
        migrations.AddField(
            model_name='clientepf',
            name='coordernada_o',
            field=models.CharField(default='', max_length=9, verbose_name='Coordernada Oeste'),
        ),
    ]
