# Generated by Django 5.1.6 on 2025-03-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_clientepf_coordenada_s_clientepf_coordernada_o'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientepf',
            name='coordernada_o',
        ),
        migrations.AddField(
            model_name='clientepf',
            name='coordenada_o',
            field=models.CharField(default='', max_length=9, verbose_name='Coordenada Oeste'),
        ),
    ]
