# Generated by Django 5.1.6 on 2025-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_clientepf_coordernada_o_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientepj',
            name='coordenada_o',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Coordenada Oeste'),
        ),
        migrations.AddField(
            model_name='clientepj',
            name='coordenada_s',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Coordenada Sul'),
        ),
        migrations.AlterField(
            model_name='clientepf',
            name='coordenada_o',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Coordenada Oeste'),
        ),
        migrations.AlterField(
            model_name='clientepf',
            name='coordenada_s',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='Coordenada Sul'),
        ),
    ]
