# Generated by Django 5.1.6 on 2025-02-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotogtafia',
            new_name='Fotografia',
        ),
    ]
